package org.apache.cayenne.example.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.example.model.Artist;
import org.apache.cayenne.example.model.Exhibit;
import org.apache.cayenne.example.model.PaintingInfo;
import org.apache.cayenne.exp.Property;

/**
 * Class _Painting was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Painting extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String PAINTING_ID_PK_COLUMN = "painting_id";

    public static final Property<BigDecimal> ESTIMATED_PRICE = Property.create("estimatedPrice", BigDecimal.class);
    public static final Property<String> PAINTING_DESCRIPTION = Property.create("paintingDescription", String.class);
    public static final Property<String> PAINTING_TITLE = Property.create("paintingTitle", String.class);
    public static final Property<Artist> ARTIST = Property.create("artist", Artist.class);
    public static final Property<List<Exhibit>> EXHIBITS = Property.create("exhibits", List.class);
    public static final Property<PaintingInfo> PAINTING = Property.create("painting", PaintingInfo.class);

    protected BigDecimal estimatedPrice;
    protected String paintingDescription;
    protected String paintingTitle;

    protected Object artist;
    protected Object exhibits;
    protected Object painting;

    public void setEstimatedPrice(BigDecimal estimatedPrice) {
        beforePropertyWrite("estimatedPrice", this.estimatedPrice, estimatedPrice);
        this.estimatedPrice = estimatedPrice;
    }

    public BigDecimal getEstimatedPrice() {
        beforePropertyRead("estimatedPrice");
        return this.estimatedPrice;
    }

    public void setPaintingDescription(String paintingDescription) {
        beforePropertyWrite("paintingDescription", this.paintingDescription, paintingDescription);
        this.paintingDescription = paintingDescription;
    }

    public String getPaintingDescription() {
        beforePropertyRead("paintingDescription");
        return this.paintingDescription;
    }

    public void setPaintingTitle(String paintingTitle) {
        beforePropertyWrite("paintingTitle", this.paintingTitle, paintingTitle);
        this.paintingTitle = paintingTitle;
    }

    public String getPaintingTitle() {
        beforePropertyRead("paintingTitle");
        return this.paintingTitle;
    }

    public void setArtist(Artist artist) {
        setToOneTarget("artist", artist, true);
    }

    public Artist getArtist() {
        return (Artist)readProperty("artist");
    }

    public void addToExhibits(Exhibit obj) {
        addToManyTarget("exhibits", obj, true);
    }

    public void removeFromExhibits(Exhibit obj) {
        removeToManyTarget("exhibits", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Exhibit> getExhibits() {
        return (List<Exhibit>)readProperty("exhibits");
    }

    public void setPainting(PaintingInfo painting) {
        setToOneTarget("painting", painting, true);
    }

    public PaintingInfo getPainting() {
        return (PaintingInfo)readProperty("painting");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "estimatedPrice":
                return this.estimatedPrice;
            case "paintingDescription":
                return this.paintingDescription;
            case "paintingTitle":
                return this.paintingTitle;
            case "artist":
                return this.artist;
            case "exhibits":
                return this.exhibits;
            case "painting":
                return this.painting;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "estimatedPrice":
                this.estimatedPrice = (BigDecimal)val;
                break;
            case "paintingDescription":
                this.paintingDescription = (String)val;
                break;
            case "paintingTitle":
                this.paintingTitle = (String)val;
                break;
            case "artist":
                this.artist = val;
                break;
            case "exhibits":
                this.exhibits = val;
                break;
            case "painting":
                this.painting = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.estimatedPrice);
        out.writeObject(this.paintingDescription);
        out.writeObject(this.paintingTitle);
        out.writeObject(this.artist);
        out.writeObject(this.exhibits);
        out.writeObject(this.painting);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.estimatedPrice = (BigDecimal)in.readObject();
        this.paintingDescription = (String)in.readObject();
        this.paintingTitle = (String)in.readObject();
        this.artist = in.readObject();
        this.exhibits = in.readObject();
        this.painting = in.readObject();
    }

}
