package org.apache.cayenne.example.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.example.model.Painting;
import org.apache.cayenne.exp.Property;

/**
 * Class _PaintingInfo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaintingInfo extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String PAINTING_ID_PK_COLUMN = "painting_id";

    public static final Property<byte[]> IMAGE_BLOB = Property.create("imageBlob", byte[].class);
    public static final Property<String> REVIEW = Property.create("review", String.class);
    public static final Property<Painting> PAINTING = Property.create("painting", Painting.class);

    protected byte[] imageBlob;
    protected String review;

    protected Object painting;

    public void setImageBlob(byte[] imageBlob) {
        beforePropertyWrite("imageBlob", this.imageBlob, imageBlob);
        this.imageBlob = imageBlob;
    }

    public byte[] getImageBlob() {
        beforePropertyRead("imageBlob");
        return this.imageBlob;
    }

    public void setReview(String review) {
        beforePropertyWrite("review", this.review, review);
        this.review = review;
    }

    public String getReview() {
        beforePropertyRead("review");
        return this.review;
    }

    public void setPainting(Painting painting) {
        setToOneTarget("painting", painting, true);
    }

    public Painting getPainting() {
        return (Painting)readProperty("painting");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "imageBlob":
                return this.imageBlob;
            case "review":
                return this.review;
            case "painting":
                return this.painting;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "imageBlob":
                this.imageBlob = (byte[])val;
                break;
            case "review":
                this.review = (String)val;
                break;
            case "painting":
                this.painting = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.imageBlob);
        out.writeObject(this.review);
        out.writeObject(this.painting);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.imageBlob = (byte[])in.readObject();
        this.review = (String)in.readObject();
        this.painting = in.readObject();
    }

}
